# Generated by Django 3.2.16 on 2023-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Others_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('institution_or_person_in_charge', models.CharField(max_length=30)),
                ('project_objective', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Our_collaborative_institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituion_name', models.CharField(max_length=30)),
                ('institution_reason_to_colaborate', models.CharField(max_length=500)),
                ('institution_vision_of_animals', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Our_dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=30)),
                ('dog_age', models.IntegerField()),
                ('dog_history', models.CharField(max_length=500)),
                ('dog_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=30)),
                ('volunteer_age', models.IntegerField()),
                ('volunteer_reason_to_be_a_volunter', models.CharField(max_length=500)),
                ('volunteer_favourite_dog_and_reason', models.CharField(max_length=500)),
            ],
        ),
    ]
