# Generated by Django 3.2.16 on 2023-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='others_projects',
            name='image',
            field=models.ImageField(default='', upload_to='Others projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_collaborative_institutions',
            name='image',
            field=models.ImageField(default='', upload_to='Our collaborative institutions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_dogs',
            name='image',
            field=models.ImageField(default='', upload_to='Our dogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_volunteers',
            name='image',
            field=models.ImageField(default='', upload_to='Our volunteers'),
            preserve_default=False,
        ),
    ]
