# Generated by Django 3.2.16 on 2023-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_rename_volunteer_reason_to_be_a_volunter_our_volunteers_volunteer_reason_to_be_a_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_dogs',
            name='dog_status',
            field=models.BooleanField(default=True),
        ),
    ]
