# Generated by Django 3.2.16 on 2023-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_our_dogs_dog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_dogs',
            name='dog_status',
            field=models.BooleanField(),
        ),
    ]
