# Generated by Django 3.2.16 on 2023-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_alter_our_dogs_dog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurDogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=30)),
                ('dog_age', models.IntegerField()),
                ('dog_history', models.CharField(max_length=500)),
                ('dog_status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='Our dogs')),
            ],
        ),
        migrations.RenameModel(
            old_name='Others_projects',
            new_name='OthersProjects',
        ),
        migrations.RenameModel(
            old_name='Our_collaborative_institutions',
            new_name='OurCollaborativeInstitutions',
        ),
        migrations.RenameModel(
            old_name='Our_volunteers',
            new_name='OurVolunteers',
        ),
        migrations.DeleteModel(
            name='Our_dogs',
        ),
    ]
