# Generated by Django 3.2.16 on 2023-01-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_auto_20230120_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourdogs',
            old_name='dog_age',
            new_name='edad_del_perro',
        ),
    ]
