# Generated by Django 3.2.16 on 2023-01-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_rename_dog_age_ourdogs_edad_del_perro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourdogs',
            old_name='edad_del_perro',
            new_name='dog_age',
        ),
    ]
