# Generated by Django 3.2.16 on 2023-01-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_auto_20230124_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othersprojects',
            old_name='image',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='ourcollaborativeinstitutions',
            old_name='image',
            new_name='institution_image',
        ),
        migrations.RenameField(
            model_name='ourdogs',
            old_name='image',
            new_name='dog_image',
        ),
        migrations.RenameField(
            model_name='ourvolunteers',
            old_name='image',
            new_name='volunteer_image',
        ),
    ]
