# Generated by Django 3.2.16 on 2023-01-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_auto_20230131_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersprojects',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='ourcollaborativeinstitutions',
            name='institution_image',
        ),
        migrations.RemoveField(
            model_name='ourdogs',
            name='dog_image',
        ),
        migrations.RemoveField(
            model_name='ourvolunteers',
            name='volunteer_image',
        ),
    ]
